name = "AOCA Drif"
author = "Drif"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6eaad8c72e2c0ae772fad2e29505f4fa87a78d0773ad5b55deebd523778b59f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
