name = "AOCA Drif"
author = "Drif"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "683c48134f9f70a3cafa9b6582ab57853c9be2b2d2503998266712d461f466e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.232"
